import{a as L,S,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q="51470641-9c85038c1716f2f4dcdf71359",v="https://pixabay.com/api/",E=15;async function y(n){const o={key:q,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page};try{return(await L.get(v,{params:o})).data}catch{throw new Error("Failed to fetch images")}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const o=n.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o),P.refresh()}function R(){p.innerHTML=""}function m(){f.style.display="block"}function b(){f.style.display="none"}function w(){h.style.display="block"}function i(){h.style.display="none"}const B=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more-btn");let a=1,c="",d=0;B.addEventListener("submit",async n=>{n.preventDefault();const o=$.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}a=1,c=o,i(),m(),R();try{const e=await y(c,a);if(d=e.totalHits,e.hits.length===0){s.info({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040"});return}g(e.hits),e.hits.length<15||e.hits.length>=d?(s.info({title:"End",message:"Weʼre sorry, but youʼve reached the end of search results.",position:"topRight"}),i()):w()}catch{s.error({title:"Error",position:"topRight",message:"Something went wrong. Please try again later."})}finally{b()}});M.addEventListener("click",async()=>{a+=1,i(),m();try{const n=await y(c,a);g(n.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=d?(s.info({title:"End",message:"Weʼre sorry, but youʼve reached the end of search results.",position:"topRight"}),i()):w()}catch{s.error({title:"Error",message:"Something went wrong loading more.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
