import{a as L,S,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q="51470641-9c85038c1716f2f4dcdf71359",v="https://pixabay.com/api/",E=15;async function y(n,o=1){const e={key:q,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:o};try{return(await L.get(v,{params:e})).data}catch{throw new Error("Failed to fetch images")}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const o=n.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o),P.refresh()}function R(){p.innerHTML=""}function m(){f.style.display="block"}function b(){f.style.display="none"}function w(){h.style.display="block"}function a(){h.style.display="none"}const B=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more-btn");let l=1,d="",u=0;B.addEventListener("submit",async n=>{n.preventDefault();const o=$.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}l=1,d=o,a(),m(),R();try{const e=await y(d,l);if(u=e.totalHits,e.hits.length===0){s.info({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040"});return}g(e.hits),e.hits.length<15||e.hits.length>=u?(s.info({title:"End",message:"Weʼre sorry, but youʼve reached the end of search results.",position:"topRight"}),a()):w()}catch{s.error({title:"Error",position:"topRight",message:"Something went wrong. Please try again later."})}finally{b()}});M.addEventListener("click",async()=>{l+=1,a(),m();try{const n=await y(d,l);g(n.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=u?(s.info({title:"End",message:"Weʼre sorry, but youʼve reached the end of search results.",position:"topRight"}),a()):w()}catch{s.error({title:"Error",message:"Something went wrong loading more.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
